# Generated by Django 2.1.2 on 2018-11-12 12:35

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consensus', models.BooleanField()),
                ('difficulty', models.DecimalField(decimal_places=100, max_digits=120)),
                ('gas_limit', models.DecimalField(decimal_places=100, max_digits=120)),
                ('gas_used', models.DecimalField(decimal_places=100, max_digits=120)),
                ('hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(blank=True, max_length=255)),
                ('number', models.BigIntegerField()),
                ('size', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('total_difficulty', models.DecimalField(decimal_places=100, max_digits=120)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Address')),
                ('parent_hash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blocks.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_range', django.contrib.postgres.fields.ranges.BigIntegerRangeField()),
                ('reward', models.DecimalField(decimal_places=100, max_digits=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondDegreeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uncle_fetched_at', models.BigIntegerField()),
                ('nephew_hash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nephew_block_relation', to='blocks.Block')),
                ('uncle_hash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uncle_block_relation', to='blocks.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
