# Generated by Django 2.1.3 on 2018-12-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='consensus',
            field=models.BooleanField(null=True),
        ),
    ]
