# Generated by Django 2.1.3 on 2018-12-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20181209_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='parent_hash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blocks.Block', to_field='hash'),
        ),
    ]
