# Generated by Django 2.1.3 on 2019-01-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_auto_20181209_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='block',
            name='gas_limit',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='block',
            name='gas_used',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='block',
            name='total_difficulty',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='blockreward',
            name='reward',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
    ]
