# Generated by Django 2.1.4 on 2019-01-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20190122_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='block',
            name='gas_limit',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='block',
            name='gas_used',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='block',
            name='total_difficulty',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='blockreward',
            name='reward',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
    ]
