# Generated by Django 2.1.2 on 2018-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('opening_price', models.DecimalField(decimal_places=100, max_digits=120)),
                ('closing_price', models.DecimalField(decimal_places=100, max_digits=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
