# Generated by Django 2.1.3 on 2019-01-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethistory',
            name='closing_price',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='opening_price',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
    ]
