# Generated by Django 2.1.4 on 2019-01-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20190122_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethistory',
            name='closing_price',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='opening_price',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
    ]
