# Generated by Django 2.1.2 on 2018-11-12 12:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_type', models.CharField(max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('gas', models.DecimalField(decimal_places=100, max_digits=120, null=True)),
                ('gas_used', models.DecimalField(decimal_places=100, max_digits=120, null=True)),
                ('index', models.IntegerField()),
                ('init', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('trace_address', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('type', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=100, max_digits=120)),
                ('created_contract_address_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_transaction_contract_address', to='address.Address')),
                ('from_address_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_transaction_from_address', to='address.Address')),
                ('to_address_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_transaction_to_address', to='address.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_number', models.IntegerField(null=True)),
                ('cumulative_gas_used', models.DecimalField(decimal_places=100, max_digits=120, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('gas', models.DecimalField(decimal_places=100, max_digits=120)),
                ('gas_price', models.DecimalField(decimal_places=100, max_digits=120)),
                ('gas_used', models.DecimalField(decimal_places=100, max_digits=120, null=True)),
                ('hash', models.CharField(max_length=255)),
                ('index', models.IntegerField(null=True)),
                ('input', models.TextField()),
                ('internal_transactions_indexed_at', models.BigIntegerField(null=True)),
                ('nonce', models.IntegerField()),
                ('r', models.DecimalField(decimal_places=100, max_digits=120)),
                ('s', models.DecimalField(decimal_places=100, max_digits=120)),
                ('status', models.IntegerField(null=True)),
                ('v', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=100, max_digits=120)),
                ('block_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
                ('created_contract_address_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_contract_address', to='address.Address')),
                ('from_address_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from_address', to='address.Address')),
                ('to_address_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to_address', to='address.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='internaltransaction',
            name='transaction_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='fork',
            name='hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='fork',
            name='uncle_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Block'),
        ),
    ]
