# Generated by Django 2.1.3 on 2019-01-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='r',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='s',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=20, max_digits=120),
        ),
    ]
