# Generated by Django 2.1.3 on 2019-01-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190120_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransaction',
            name='gas',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='gas_used',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='value',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cumulative_gas_used',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas_price',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas_used',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=18, max_digits=120),
        ),
    ]
