# Generated by Django 2.1.4 on 2019-01-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190122_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransaction',
            name='gas',
            field=models.DecimalField(decimal_places=0, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='gas_used',
            field=models.DecimalField(decimal_places=0, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cumulative_gas_used',
            field=models.DecimalField(decimal_places=0, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas_price',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gas_used',
            field=models.DecimalField(decimal_places=0, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
    ]
