# Generated by Django 2.1.2 on 2018-11-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstokenbalance',
            name='token_contract_address_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.Token'),
        ),
        migrations.AddField(
            model_name='addressname',
            name='address_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Address'),
        ),
        migrations.AddField(
            model_name='addresscoinbalance',
            name='address_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Address'),
        ),
    ]
