# Generated by Django 2.1.3 on 2019-01-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20181209_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coin_balance',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='addresscoinbalance',
            name='value',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='addresstokenbalance',
            name='value',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
    ]
