# Generated by Django 2.1.2 on 2018-11-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
                ('first_topic', models.CharField(max_length=255)),
                ('second_topic', models.CharField(max_length=255)),
                ('third_topic', models.CharField(max_length=255)),
                ('fourth_topic', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField()),
                ('address_hash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Address')),
                ('transaction_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
