# Generated by Django 2.1.3 on 2019-01-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='total_supply',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='tokentransfer',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=120, null=True),
        ),
    ]
